name: JavaScript CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies and build
        working-directory: ./front_end
        run: |
          npm install
          npm run build
          ls -la  # Debug: Show all files in front_end/
          ls -la build/ || echo "Build directory not found"  # Debug: Confirm build/ exists

      - name: Prepare deployment package
        run: |
          mkdir -p dist/public
          cp back_end/server.js dist/
          cp back_end/package.json dist/
          cp back_end/package-lock.json dist/
          if [ -d "front_end/build" ]; then
            cp -r front_end/build/* dist/public/
          else
            echo "Error: front_end/build directory not found"
            exit 1
          fi
          cd dist
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D18D7A4EC314C288921152D2118FC08 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5C5007CFF6BA4FB5B49E0DC3192C86D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4AA54E0F3D774CCB86144B21F8990B2B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Trello'
          slot-name: 'Production'
          package: .
