name: JavaScript CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies locally
        working-directory: ./back_end
        run: npm install

      - name: Install frontend dependencies and build
        working-directory: ./front_end
        run: |
          npm install
          npm run build
          ls -la
          ls -la build/ || echo "Build directory not found"

      - name: Prepare deployment package
        run: |
          mkdir -p dist/public
          # Copy entire back_end directory (excluding node_modules)
          cp -r back_end/* dist/
          # Remove node_modules from dist if it got copied
          rm -rf dist/node_modules
          if [ -d "front_end/build" ]; then
            cp -r front_end/build/* dist/public/
          else
            echo "Error: front_end/build directory not found"
            exit 1
          fi
          cd dist
          npm install --production  # Install dependencies in the deployment package
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D18D7A4EC314C288921152D2118FC08 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9673e9a8-aa57-4461-9336-5fd3f0034e18 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_b7a174df-9343-42b2-9d9a-de07926966e2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Trello'
          slot-name: 'Production'
          package: .
